from enum import Enum

class FaultType(Enum):
    NONE = 0
    OVERHEATING = 1
    LOW_OIL_PRESSURE = 2
    VOLTAGE_DROP = 3
    TEMP_SENSOR_FAILURE = 4
    RPM_SENSOR_FAILURE = 5
    VOLTAGE_SENSOR_FAILURE = 6
    PRESSURE_SENSOR_FAILURE = 7
    VOLTAGE_ZERO = 8
    TEMP_ZERO = 9
    PRESSURE_ZERO = 10
    RPM_ZERO = 11