from enum import Enum

class FaultType(Enum):
    NONE = 0
    OVERHEATING = 1
    LOW_OIL_PRESSURE = 2
    VOLTAGE_DROP = 3
    RPM_DROP = 4
    TEMP_SENSOR_FAILURE = 5
    RPM_SENSOR_FAILURE = 6
    VOLTAGE_SENSOR_FAILURE = 7
    PRESSURE_SENSOR_FAILURE = 8
    VOLTAGE_ZERO = 9
    TEMP_ZERO = 10
    PRESSURE_ZERO = 11
    RPM_ZERO = 12